abstract final class PerformancePermissions {
  /// Means "may see **other people's** reviews".
  ///
  /// Not a gate on the module as a whole: `guardOwnReviewAccess` lets any
  /// employee read their own regardless, and the service says why in a comment
  /// — a flat permission check there would have locked people out of their own
  /// appraisal. So the app gates the team list on this and never the personal
  /// one.
  static const view = 'PERFORMANCE_VIEW';

  /// Editing, advancing a stage, and finalising.
  static const update = 'PERFORMANCE_UPDATE';
}

/// The stages a review moves through, in order.
abstract final class PerformanceStage {
  static const selfAssessment = 'SELF_ASSESSMENT';
  static const managerReview = 'MANAGER_REVIEW';
  static const hrApproval = 'HR_APPROVAL';
  static const finalApproval = 'FINAL_APPROVAL';
  static const completed = 'COMPLETED';

  static const ordered = [
    selfAssessment,
    managerReview,
    hrApproval,
    finalApproval,
    completed,
  ];

  static const labels = {
    selfAssessment: 'Self assessment',
    managerReview: 'Manager review',
    hrApproval: 'HR approval',
    finalApproval: 'Final approval',
    completed: 'Completed',
  };
}

/// One scored dimension of a review.
class ReviewScore {
  const ReviewScore(this.label, this.value);

  final String label;
  final int? value;
}

class PerformanceReview {
  const PerformanceReview({
    required this.id,
    required this.stage,
    required this.finalised,
    this.employeeId,
    this.employeeName,
    this.reviewedByName,
    this.reviewPeriodStart,
    this.reviewPeriodEnd,
    this.overallScore,
    this.scoreWorkQuality,
    this.scoreProductivity,
    this.scoreCommunication,
    this.scoreTeamwork,
    this.scoreInitiative,
    this.scorePunctuality,
    this.scoreLeadership,
    this.scoreProblemSolving,
    this.scoreInnovation,
    this.strengths,
    this.areasForImprovement,
    this.goalsForNextPeriod,
    this.comments,
    this.performanceLevel,
    this.promotionRecommendation,
    this.promotionReadiness,
    this.trainingRecommendation,
    this.recognition,
    this.goalCompletionPercent,
    this.aiSummary,
    this.createdAt,
  });

  final int id;
  final String stage;
  final bool finalised;
  final int? employeeId;
  final String? employeeName;
  final String? reviewedByName;
  final String? reviewPeriodStart;
  final String? reviewPeriodEnd;
  final double? overallScore;

  final int? scoreWorkQuality;
  final int? scoreProductivity;
  final int? scoreCommunication;
  final int? scoreTeamwork;
  final int? scoreInitiative;
  final int? scorePunctuality;
  final int? scoreLeadership;
  final int? scoreProblemSolving;
  final int? scoreInnovation;

  final String? strengths;
  final String? areasForImprovement;
  final String? goalsForNextPeriod;
  final String? comments;
  final String? performanceLevel;
  final String? promotionRecommendation;
  final String? promotionReadiness;
  final String? trainingRecommendation;
  final String? recognition;
  final int? goalCompletionPercent;

  /// Generated by the AI module. Labelled as such wherever it is shown — a
  /// machine's summary of somebody's year should never be mistaken for their
  /// manager's words.
  final String? aiSummary;

  final String? createdAt;

  String get personLabel => employeeName?.trim().isNotEmpty == true
      ? employeeName!.trim()
      : 'Employee #${employeeId ?? id}';

  String get stageLabel =>
      PerformanceStage.labels[stage] ?? stage.replaceAll('_', ' ');

  int get stageIndex {
    final i = PerformanceStage.ordered.indexOf(stage);
    return i < 0 ? 0 : i;
  }

  bool get isComplete => stage == PerformanceStage.completed;

  /// A finalised review is a signed record. Nothing can move it on, and the
  /// screen must not offer to.
  bool get canAdvance => !finalised && !isComplete;

  /// Only a review that has reached the end can be signed off.
  bool get canFinalise => !finalised && isComplete;

  String? get period {
    final start = reviewPeriodStart;
    final end = reviewPeriodEnd;
    if (start == null && end == null) return null;
    return '${start ?? '?'} → ${end ?? '?'}';
  }

  /// The nine scored dimensions, in the order the form asks for them. Every
  /// one is optional, so the detail screen shows only those that were filled.
  List<ReviewScore> get scores => [
        ReviewScore('Work quality', scoreWorkQuality),
        ReviewScore('Productivity', scoreProductivity),
        ReviewScore('Communication', scoreCommunication),
        ReviewScore('Teamwork', scoreTeamwork),
        ReviewScore('Initiative', scoreInitiative),
        ReviewScore('Punctuality', scorePunctuality),
        ReviewScore('Leadership', scoreLeadership),
        ReviewScore('Problem solving', scoreProblemSolving),
        ReviewScore('Innovation', scoreInnovation),
      ];

  List<ReviewScore> get filledScores =>
      scores.where((s) => s.value != null).toList(growable: false);

  bool get hasScores => filledScores.isNotEmpty;

  /// The written half. Empty strings are treated as absent so a blank section
  /// never renders as a heading with nothing under it.
  List<({String title, String body})> get narrative {
    final sections = <({String title, String? body})>[
      (title: 'Strengths', body: strengths),
      (title: 'Areas to improve', body: areasForImprovement),
      (title: 'Goals for next period', body: goalsForNextPeriod),
      (title: 'Training suggested', body: trainingRecommendation),
      (title: 'Recognition', body: recognition),
      (title: 'Comments', body: comments),
    ];
    return [
      for (final s in sections)
        if (s.body?.trim().isNotEmpty == true)
          (title: s.title, body: s.body!.trim()),
    ];
  }

  factory PerformanceReview.fromJson(Map<String, dynamic> json) =>
      PerformanceReview(
        id: (json['id'] as num?)?.toInt() ?? 0,
        stage: json['stage'] as String? ?? PerformanceStage.selfAssessment,
        finalised: json['finalised'] as bool? ?? false,
        employeeId: (json['employeeId'] as num?)?.toInt(),
        employeeName: json['employeeName'] as String?,
        reviewedByName: json['reviewedByName'] as String?,
        reviewPeriodStart: json['reviewPeriodStart'] as String?,
        reviewPeriodEnd: json['reviewPeriodEnd'] as String?,
        overallScore: (json['overallScore'] as num?)?.toDouble(),
        scoreWorkQuality: (json['scoreWorkQuality'] as num?)?.toInt(),
        scoreProductivity: (json['scoreProductivity'] as num?)?.toInt(),
        scoreCommunication: (json['scoreCommunication'] as num?)?.toInt(),
        scoreTeamwork: (json['scoreTeamwork'] as num?)?.toInt(),
        scoreInitiative: (json['scoreInitiative'] as num?)?.toInt(),
        scorePunctuality: (json['scorePunctuality'] as num?)?.toInt(),
        scoreLeadership: (json['scoreLeadership'] as num?)?.toInt(),
        scoreProblemSolving: (json['scoreProblemSolving'] as num?)?.toInt(),
        scoreInnovation: (json['scoreInnovation'] as num?)?.toInt(),
        strengths: json['strengths'] as String?,
        areasForImprovement: json['areasForImprovement'] as String?,
        goalsForNextPeriod: json['goalsForNextPeriod'] as String?,
        comments: json['comments'] as String?,
        performanceLevel: json['performanceLevel'] as String?,
        promotionRecommendation: json['promotionRecommendation'] as String?,
        promotionReadiness: json['promotionReadiness'] as String?,
        trainingRecommendation: json['trainingRecommendation'] as String?,
        recognition: json['recognition'] as String?,
        goalCompletionPercent:
            (json['goalCompletionPercent'] as num?)?.toInt(),
        aiSummary: json['aiSummary'] as String?,
        createdAt: json['createdAt'] as String?,
      );
}
